[package]
name = "bib"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common/" }

[dev-dependencies]
tectonic_tester = { path = "../tectonic_tester/" }
